name: Event
description: Event plugin for adding events

author: Thomas Rader
authorEmail: thomas.rader@tigerclawtech.com
authorUrl: http://tigerclawtech.com/croogo/plugins

dependencies:
  plugins:
    - acl
    - extensions